from __future__ import annotations

from pathlib import Path

from tests.helpers import subprocess_cli as cli_subprocess

run_belgi = cli_subprocess.run_belgi


def test_init_creates_operator_readme_with_required_sections(tmp_path: Path) -> None:
    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    readme_path = tmp_path / ".belgi" / "README.md"
    assert readme_path.is_file()

    text = readme_path.read_text(encoding="utf-8", errors="strict")
    expected_sections = (
        "Generated by `belgi init`",
        "may be overwritten deterministically",
        "## Quickstart",
        "belgi init --repo .",
        "belgi run new --repo . --run-id run-001",
        "belgi run --repo . --tier tier-1 --intent-spec .belgi/runs/run-001/inputs/intent/IntentSpec.core.md --base-revision <SHA40>",
        "--toolchain-set-ref env.toolchains=.belgi/runs/run-001/inputs/environment/toolchain-set.json",
        "--toolchain-ref deps.requirements=requirements.txt",
        "--tolerances-ref tier.tolerances=.belgi/runs/run-001/inputs/environment/tolerances.json",
        "Optional shared run object inputs:",
        "belgi verify --repo .",
        "## Layout map",
        ".belgi/runs/<run_id>/",
        ".belgi/store/runs/<run_key>/<attempt_id>/",
        "open_verdict.txt",
        "open_evidence.txt",
        "## On NO-GO",
        "For public `NO-GO (10)` output, check `next` first.",
        "gate_verdict_path",
        "evidence_manifest_path",
        "## What this is",
        "## What this is not",
    )
    for snippet in expected_sections:
        assert snippet in text


def test_init_rewrites_operator_readme_deterministically(tmp_path: Path) -> None:
    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    readme_path = tmp_path / ".belgi" / "README.md"
    baseline = readme_path.read_bytes()
    assert b"\r\n" not in baseline

    readme_path.write_text("drifted-content\n", encoding="utf-8", errors="strict", newline="\n")
    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    repaired = readme_path.read_bytes()
    assert repaired == baseline

    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    assert readme_path.read_bytes() == baseline
