from __future__ import annotations

from pathlib import Path

from tests.helpers import subprocess_cli as cli_subprocess

run_belgi = cli_subprocess.run_belgi


def test_init_creates_operator_readme_with_required_sections(tmp_path: Path) -> None:
    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    readme_path = tmp_path / ".belgi" / "README.md"
    assert readme_path.is_file()

    text = readme_path.read_text(encoding="utf-8", errors="strict")
    assert "Generated by `belgi init`" in text
    assert "may be overwritten deterministically" in text
    assert "## Quickstart" in text
    assert "belgi init --repo ." in text
    assert "belgi run new --repo . --run-id run-001" in text
    assert (
        "belgi run --repo . --tier tier-1 --intent-spec .belgi/runs/run-001/inputs/intent/IntentSpec.core.md --base-revision <SHA40>"
        in text
    )
    assert "--toolchain-set-ref env.toolchains=.belgi/runs/run-001/inputs/environment/toolchain-set.json" in text
    assert "--toolchain-ref deps.requirements=requirements.txt" in text
    assert "--tolerances-ref tier.tolerances=.belgi/runs/run-001/inputs/environment/tolerances.json" in text
    assert "Optional shared run object inputs:" in text
    assert "Use `--toolchain-set-ref <object_id>=<repo-relative-path>`" in text
    assert "Repeat `--toolchain-ref <object_id>=<repo-relative-path>`" in text
    assert "Use `--tolerances-ref <object_id>=<repo-relative-path>`" in text
    assert "Explicit ToolchainSet refs are pre-lock operator inputs." in text
    assert "Accepted only as the current run canonical input:" in text
    assert "stages that ToolchainSet into locked/store authority before C1" in text
    assert (
        "ToolchainSet member declaration paths must still point at actual repo-relative dependency/toolchain declaration surfaces in the evaluated revision truth envelope."
        in text
    )
    assert "Explicit Tolerances refs are pre-lock operator inputs." in text
    assert "stages that Tolerances object into locked/store authority before C1" in text
    assert "`Tolerances.tier_id` must match the selected tier." in text
    assert "may equal or tighten the selected tier ceilings, but BELGI rejects wider values" in text
    assert "`toolchain.main` is reserved" in text
    assert "materializes the canonical Tolerances object from the selected tier pack" in text
    assert "belgi verify --repo ." in text
    assert "## Layout map" in text
    assert ".belgi/runs/<run_id>/" in text
    assert ".belgi/store/runs/<run_key>/<attempt_id>/" in text
    assert "open_verdict.txt" in text
    assert "open_evidence.txt" in text
    assert "## On NO-GO" in text
    assert "For public `NO-GO (10)` output, check `next` first." in text
    assert "GateVerdict.<Q|R|S>.json remediation.next_instruction" in text
    assert "C1IntentParseError.json next_instruction" in text
    assert "Separate public `USER_ERROR (20)` failures use direct CLI guidance" in text
    assert "gate_verdict_path" in text
    assert "evidence_manifest_path" in text
    assert "## What this is" in text
    assert "## What this is not" in text


def test_init_rewrites_operator_readme_deterministically(tmp_path: Path) -> None:
    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    readme_path = tmp_path / ".belgi" / "README.md"
    baseline = readme_path.read_bytes()
    assert b"\r\n" not in baseline

    readme_path.write_text("drifted-content\n", encoding="utf-8", errors="strict", newline="\n")
    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    repaired = readme_path.read_bytes()
    assert repaired == baseline

    assert run_belgi(["init", "--repo", str(tmp_path)]) == 0
    assert readme_path.read_bytes() == baseline
