from __future__ import annotations

import importlib
import inspect
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from belgi.commands.adversarial_scan import run_adversarial_scan
from belgi.commands.supplychain_scan import run_supplychain_scan
from belgi.core.command_log import append_command_to_manifest
from belgi.core.hash import sha256_bytes
from belgi.core.jail import safe_relpath
from belgi.core.schema import validate_schema


CHAIN_REPO_DIRNAME = "repo"
CHAIN_OUT_DIRNAME = "out"
FIXED_GENERATED_AT = "1970-01-01T00:00:00Z"
FIXED_SEALED_AT = "2000-01-01T00:30:00Z"
FIXED_SIGNER = "human:belgi-run"

_SHA256_RE = re.compile(r"^[0-9a-fA-F]{64}$")


@dataclass(frozen=True)
class RunOrchestrationResult:
    chain_repo_dir: Path
    chain_out_dir: Path
    rel_evidence_final: str
    rel_seal: str
    rel_gate_s: str
    chain_paths: list[Path]


def render_default_intent_spec(*, tier_id: str) -> bytes:
    text = (
        "# IntentSpec (auto-generated by belgi run)\n\n"
        "```yaml\n"
        'intent_id: "INTENT-AUTO-RUN"\n'
        'title: "Deterministic BELGI chain run"\n'
        'goal: "Execute the canonical BELGI chain to Seal deterministically."\n'
        "scope:\n"
        "  allowed_dirs:\n"
        '    - "belgi/"\n'
        "  forbidden_dirs:\n"
        '    - "main/"\n'
        "acceptance:\n"
        "  success_criteria:\n"
        '    - "Gate Q, Gate R, and Gate S return GO."\n'
        "tier:\n"
        f'  tier_pack_id: "{tier_id}"\n'
        "doc_impact:\n"
        "  required_paths: []\n"
        '  note_on_empty: "No documentation updates are required for this deterministic workspace run."\n'
        "publication_intent:\n"
        "  publish: true\n"
        '  profile: "public"\n'
        "```\n"
    )
    return text.encode("utf-8", errors="strict")


def _invoke_module_main(module_name: str, argv: list[str]) -> int:
    module = importlib.import_module(module_name)
    main_fn = getattr(module, "main", None)
    if not callable(main_fn):
        raise ValueError(f"{module_name} does not expose a callable main()")

    try:
        sig = inspect.signature(main_fn)
    except Exception:
        sig = None

    try:
        if sig is not None and len(sig.parameters) == 0:
            old_argv = sys.argv
            sys.argv = [module_name, *argv]
            try:
                rc = main_fn()
            finally:
                sys.argv = old_argv
        else:
            rc = main_fn(argv)
    except SystemExit as e:
        if isinstance(e.code, int):
            return e.code
        return 3

    if rc is None:
        return 0
    if not isinstance(rc, int):
        raise ValueError(f"{module_name} returned non-integer exit code: {rc!r}")
    return rc


def _run_module_expect_rc(module_name: str, argv: list[str], *, allowed: tuple[int, ...] = (0,)) -> None:
    rc = _invoke_module_main(module_name, argv)
    if rc not in allowed:
        raise ValueError(f"{module_name} returned rc={rc}")


def _run_tools_belgi(repo_root: Path, argv: list[str], *, allowed: tuple[int, ...] = (0,)) -> int:
    rc = _invoke_module_main("tools.belgi_tools", [*argv, "--repo", str(repo_root)])
    if rc not in allowed:
        raise ValueError(f"tools.belgi_tools {' '.join(argv)} returned rc={rc}")
    return rc


def _git_clone_at_commit(*, source_repo: Path, dest_repo: Path, commit_sha: str) -> None:
    if dest_repo.exists():
        raise ValueError(f"clone destination already exists: {dest_repo}")

    cp_clone = subprocess.run(
        ["git", "clone", "--quiet", "--shared", "--", str(source_repo), str(dest_repo)],
        capture_output=True,
        text=True,
        check=False,
    )
    if cp_clone.returncode != 0:
        msg = (cp_clone.stderr or cp_clone.stdout or "").strip()
        raise ValueError(f"git clone failed: {msg or 'unknown error'}")

    cp_checkout = subprocess.run(
        ["git", "-C", str(dest_repo), "checkout", "--quiet", commit_sha],
        capture_output=True,
        text=True,
        check=False,
    )
    if cp_checkout.returncode != 0:
        msg = (cp_checkout.stderr or cp_checkout.stdout or "").strip()
        raise ValueError(f"git checkout failed: {msg or 'unknown error'}")


def _git_diff_bytes(*, repo_root: Path, upstream: str, evaluated: str) -> bytes:
    cp = subprocess.run(
        [
            "git",
            "-C",
            str(repo_root),
            "-c",
            "core.pager=cat",
            "diff",
            "--no-color",
            "--no-ext-diff",
            "--full-index",
            upstream,
            evaluated,
            "--",
            ".",
        ],
        capture_output=True,
        check=False,
    )
    if cp.returncode != 0:
        msg = cp.stderr.decode("utf-8", errors="replace").strip()
        raise ValueError(f"git diff failed: {msg or f'rc={cp.returncode}'}")
    return cp.stdout


def _write_json(path: Path, obj: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
        errors="strict",
        newline="\n",
    )


def _load_json_object(path: Path, *, label: str) -> dict[str, object]:
    try:
        obj = json.loads(path.read_text(encoding="utf-8", errors="strict"))
    except Exception as e:
        raise ValueError(f"{label} is not valid UTF-8 JSON: {e}") from e
    if not isinstance(obj, dict):
        raise ValueError(f"{label} must be a JSON object")
    return obj


def _command_log_mode_for_tier(*, protocol: Any, tier_id: str) -> str:
    try:
        from chain.logic.tier_packs import load_tier_params
    except Exception as e:
        raise ValueError(f"tier parser unavailable for run orchestration: {e}") from e

    tiers_text = protocol.read_text("tiers/tier-packs.json")
    loaded = load_tier_params(tiers_text, tier_id)
    if loaded.params is None:
        parse_err = loaded.parse_error or "unknown parse failure"
        raise ValueError(f"tier parameter parse failed: {parse_err}")
    mode = loaded.params.command_log_mode
    if mode not in ("strings", "structured"):
        raise ValueError(f"unsupported command_log_mode for tier {tier_id}: {mode!r}")
    return str(mode)


def _append_command(
    *,
    commands_executed: list[Any],
    command_log_mode: str,
    subcommand: str,
    exit_code: int,
) -> list[Any]:
    return append_command_to_manifest(
        commands_executed,
        mode=command_log_mode,
        argv=["belgi", subcommand],
        exit_code=exit_code,
        timestamp=FIXED_GENERATED_AT,
    )


def _parse_registry_block_ids(registry_text: str) -> list[str]:
    ids = sorted(set(re.findall(r"\bPB-\d{3}\b", registry_text)))
    if not ids:
        raise ValueError("prompt block registry contains no PB-* ids")
    return ids


def _render_prompt_block_bytes(*, block_id: str, locked_spec_preimage: dict[str, object]) -> bytes:
    c1_module = importlib.import_module("chain.compiler_c1_intent")
    render_fn = getattr(c1_module, "_render_prompt_block", None)
    if not callable(render_fn):
        raise ValueError("chain.compiler_c1_intent._render_prompt_block is unavailable")
    try:
        rendered = render_fn(block_id=block_id, locked_spec_preimage=locked_spec_preimage)
    except Exception as e:
        raise ValueError(f"cannot deterministically render prompt block {block_id}: {e}") from e
    if not isinstance(rendered, (bytes, bytearray)):
        raise ValueError(f"prompt block renderer returned non-bytes for {block_id}")
    return bytes(rendered)


def _ensure_complete_prompt_block_hashes(
    *,
    chain_repo_root: Path,
    prompt_hashes_path: Path,
    locked_spec: dict[str, object],
) -> None:
    mapping_obj = _load_json_object(prompt_hashes_path, label="prompt_block_hashes.json")
    mapping: dict[str, str] = {}
    for k, v in mapping_obj.items():
        if isinstance(k, str) and isinstance(v, str):
            if not _SHA256_RE.fullmatch(v):
                raise ValueError(f"invalid prompt block hash for {k}: expected 64-hex")
            mapping[k] = v.lower()

    registry_path = chain_repo_root / "belgi" / "templates" / "PromptBundle.blocks.md"
    if not registry_path.exists() or registry_path.is_symlink() or not registry_path.is_file():
        raise ValueError(f"missing prompt block registry: {registry_path}")
    registry_text = registry_path.read_text(encoding="utf-8", errors="strict")
    required_block_ids = _parse_registry_block_ids(registry_text)

    changed = False
    for block_id in required_block_ids:
        if block_id in mapping:
            continue
        rendered = _render_prompt_block_bytes(block_id=block_id, locked_spec_preimage=locked_spec)
        mapping[block_id] = sha256_bytes(rendered)
        changed = True

    if changed:
        ordered = {k: mapping[k] for k in sorted(mapping.keys())}
        _write_json(prompt_hashes_path, ordered)


def _make_evidence_artifact(
    *,
    chain_repo_root: Path,
    path: Path,
    kind: str,
    artifact_id: str,
    media_type: str,
    produced_by: str,
) -> dict[str, str]:
    return {
        "kind": kind,
        "id": artifact_id,
        "hash": sha256_bytes(path.read_bytes()),
        "media_type": media_type,
        "storage_ref": safe_relpath(chain_repo_root, path),
        "produced_by": produced_by,
    }


def _collect_chain_artifact_paths(*, chain_repo_root: Path, chain_out_dir: Path) -> list[Path]:
    if chain_out_dir.is_symlink() or not chain_out_dir.is_dir():
        raise ValueError(f"missing chain output directory: {chain_out_dir}")

    out_files: list[Path] = []
    for p in sorted(chain_out_dir.rglob("*"), key=lambda x: x.as_posix()):
        if p.is_symlink():
            raise ValueError(f"symlink output not allowed: {p}")
        if p.is_file():
            out_files.append(p)

    extras = [
        chain_repo_root / "IntentSpec.core.md",
        chain_repo_root / "docs" / "docs_compilation_log.json",
    ]
    for p in extras:
        if not p.exists() or p.is_symlink() or not p.is_file():
            raise ValueError(f"missing required chain artifact: {p}")
        out_files.append(p)

    dedup: dict[str, Path] = {}
    for p in out_files:
        dedup[str(p.resolve())] = p
    return sorted(dedup.values(), key=lambda x: x.as_posix())


def orchestrate_chain_run(
    *,
    source_repo_root: Path,
    chain_repo_dir: Path,
    run_key: str,
    tier_id: str,
    repo_head_sha: str,
    intent_bytes: bytes,
    protocol: Any,
) -> RunOrchestrationResult:
    command_log_mode = _command_log_mode_for_tier(protocol=protocol, tier_id=tier_id)

    chain_out_dir = chain_repo_dir / CHAIN_OUT_DIRNAME
    chain_artifacts_dir = chain_out_dir / "artifacts"

    rel_locked = f"{CHAIN_OUT_DIRNAME}/LockedSpec.json"
    rel_prompt_bundle = f"{CHAIN_OUT_DIRNAME}/prompt_bundle.md"
    rel_prompt_hashes = f"{CHAIN_OUT_DIRNAME}/prompt_block_hashes.json"
    rel_prompt_policy = f"{CHAIN_OUT_DIRNAME}/policy.prompt_bundle.json"
    rel_policy_inv = f"{CHAIN_OUT_DIRNAME}/artifacts/policy.invariant_eval.json"
    rel_policy_supply = f"{CHAIN_OUT_DIRNAME}/artifacts/policy.supplychain.json"
    rel_policy_adv = f"{CHAIN_OUT_DIRNAME}/artifacts/policy.adversarial_scan.json"
    rel_command_log = f"{CHAIN_OUT_DIRNAME}/artifacts/command_log.json"
    rel_diff = f"{CHAIN_OUT_DIRNAME}/artifacts/diff.patch"
    rel_test_report = f"{CHAIN_OUT_DIRNAME}/artifacts/tests.report.json"
    rel_env_att = f"{CHAIN_OUT_DIRNAME}/artifacts/env.attestation.json"
    rel_evidence_input = f"{CHAIN_OUT_DIRNAME}/EvidenceManifest.input.json"
    rel_gate_q = f"{CHAIN_OUT_DIRNAME}/GateVerdict.Q.json"
    rel_verify_report = f"{CHAIN_OUT_DIRNAME}/verify_report.R.json"
    rel_gate_r = f"{CHAIN_OUT_DIRNAME}/GateVerdict.R.json"
    rel_r_snapshot = f"{CHAIN_OUT_DIRNAME}/EvidenceManifest.r_snapshot.json"
    rel_evidence_final = f"{CHAIN_OUT_DIRNAME}/EvidenceManifest.json"
    rel_docs = f"{CHAIN_OUT_DIRNAME}/run_docs.md"
    rel_bundle = f"{CHAIN_OUT_DIRNAME}/bundle"
    rel_bundle_root_sha = f"{CHAIN_OUT_DIRNAME}/bundle_root.sha256"
    rel_seal = f"{CHAIN_OUT_DIRNAME}/SealManifest.json"
    rel_gate_s = f"{CHAIN_OUT_DIRNAME}/GateVerdict.S.json"

    _git_clone_at_commit(source_repo=source_repo_root, dest_repo=chain_repo_dir, commit_sha=repo_head_sha)

    commands_executed: list[Any] = []
    rc_supply = run_supplychain_scan(
        repo=chain_repo_dir,
        evaluated_revision=repo_head_sha,
        out_path=chain_repo_dir / rel_policy_supply,
        deterministic=True,
        run_id=run_key,
    )
    if rc_supply != 0:
        raise ValueError(f"supplychain scan failed (rc={rc_supply})")
    commands_executed = _append_command(
        commands_executed=commands_executed,
        command_log_mode=command_log_mode,
        subcommand="supplychain-scan",
        exit_code=rc_supply,
    )

    chain_out_dir.mkdir(parents=True, exist_ok=True)
    chain_artifacts_dir.mkdir(parents=True, exist_ok=True)

    intent_in_chain = chain_repo_dir / "IntentSpec.core.md"
    intent_in_chain.write_bytes(intent_bytes)

    tolerances_path = chain_out_dir / "inputs" / "tolerances.json"
    toolchain_path = chain_out_dir / "inputs" / "toolchain.json"
    _write_json(tolerances_path, {"schema_version": "1.0.0", "tier_id": tier_id})
    _write_json(
        toolchain_path,
        {
            "schema_version": "1.0.0",
            "python_version": sys.version.split()[0],
            "runner": "belgi.cli.run",
        },
    )

    c1_argv = [
        "--repo",
        str(chain_repo_dir),
        "--intent-spec",
        "IntentSpec.core.md",
        "--out",
        rel_locked,
        "--run-id",
        run_key,
        "--repo-ref",
        repo_head_sha,
        "--prompt-bundle-out",
        rel_prompt_bundle,
        "--prompt-bundle-id",
        "prompt.bundle",
        "--prompt-block-hashes-out",
        rel_prompt_hashes,
        "--prompt-bundle-policy-out",
        rel_prompt_policy,
        "--tolerances",
        f"tier.tolerances={safe_relpath(chain_repo_dir, tolerances_path)}",
        "--envelope-id",
        "env.default",
        "--envelope-description",
        "Deterministic BELGI run envelope",
        "--expected-runner",
        "belgi.cli.run",
        "--toolchain-ref",
        f"toolchain.main={safe_relpath(chain_repo_dir, toolchain_path)}",
    ]

    ci_prev = os.environ.pop("CI", None)
    try:
        _run_module_expect_rc("chain.compiler_c1_intent", c1_argv)
    finally:
        if ci_prev is not None:
            os.environ["CI"] = ci_prev

    locked_spec_path = chain_repo_dir / rel_locked
    locked_spec = _load_json_object(locked_spec_path, label="LockedSpec.json")
    if str(locked_spec.get("run_id") or "") != run_key:
        raise ValueError("LockedSpec.run_id mismatch after C1 compilation")
    tier_obj = locked_spec.get("tier")
    locked_tier = str(tier_obj.get("tier_id") or "") if isinstance(tier_obj, dict) else ""
    if locked_tier != tier_id:
        raise ValueError(f"LockedSpec tier mismatch: expected {tier_id}, got {locked_tier or '<missing>'}")

    _ensure_complete_prompt_block_hashes(
        chain_repo_root=chain_repo_dir,
        prompt_hashes_path=chain_repo_dir / rel_prompt_hashes,
        locked_spec=locked_spec,
    )

    rc_inv = _run_tools_belgi(
        chain_repo_dir,
        ["invariant-eval", "--locked-spec", rel_locked, "--out", rel_policy_inv, "--deterministic"],
        allowed=(0,),
    )
    commands_executed = _append_command(
        commands_executed=commands_executed,
        command_log_mode=command_log_mode,
        subcommand="invariant-eval",
        exit_code=rc_inv,
    )

    rc_adv = run_adversarial_scan(
        repo=chain_repo_dir,
        out_path=chain_repo_dir / rel_policy_adv,
        deterministic=True,
        run_id=run_key,
    )
    if rc_adv != 0:
        raise ValueError(f"adversarial scan failed (rc={rc_adv})")
    commands_executed = _append_command(
        commands_executed=commands_executed,
        command_log_mode=command_log_mode,
        subcommand="adversarial-scan",
        exit_code=rc_adv,
    )

    diff_path = chain_repo_dir / rel_diff
    diff_path.parent.mkdir(parents=True, exist_ok=True)
    diff_path.write_bytes(
        _git_diff_bytes(repo_root=chain_repo_dir, upstream=repo_head_sha, evaluated=repo_head_sha)
    )

    command_log_path = chain_repo_dir / rel_command_log
    test_report_path = chain_repo_dir / rel_test_report
    env_att_path = chain_repo_dir / rel_env_att

    envelope_attestation: dict[str, str] | None = None
    if tier_id == "tier-1":
        rc_tests = _run_tools_belgi(
            chain_repo_dir,
            [
                "run-tests",
                "--run-id",
                run_key,
                "--out",
                rel_test_report,
                "--test-path",
                "tests/test_import_graph_sanity.py",
                "--deterministic",
            ],
            allowed=(0,),
        )
        commands_executed = _append_command(
            commands_executed=commands_executed,
            command_log_mode=command_log_mode,
            subcommand="run-tests",
            exit_code=rc_tests,
        )

        commands_with_att = _append_command(
            commands_executed=commands_executed,
            command_log_mode=command_log_mode,
            subcommand="verify-attestation",
            exit_code=0,
        )
        _write_json(
            command_log_path,
            {"schema_version": "1.0.0", "run_id": run_key, "commands_executed": commands_with_att},
        )

        rc_att = _run_tools_belgi(
            chain_repo_dir,
            [
                "verify-attestation",
                "--run-id",
                run_key,
                "--command-log",
                rel_command_log,
                "--locked-spec",
                rel_locked,
                "--out",
                rel_env_att,
                "--deterministic",
            ],
            allowed=(0,),
        )
        commands_executed = _append_command(
            commands_executed=commands_executed,
            command_log_mode=command_log_mode,
            subcommand="verify-attestation",
            exit_code=rc_att,
        )
        _write_json(
            command_log_path,
            {"schema_version": "1.0.0", "run_id": run_key, "commands_executed": commands_executed},
        )

        envelope_attestation = {
            "id": "env.attestation",
            "hash": sha256_bytes(env_att_path.read_bytes()),
            "storage_ref": safe_relpath(chain_repo_dir, env_att_path),
        }
    else:
        _write_json(
            command_log_path,
            {"schema_version": "1.0.0", "run_id": run_key, "commands_executed": commands_executed},
        )

    artifacts = [
        _make_evidence_artifact(
            chain_repo_root=chain_repo_dir,
            path=locked_spec_path,
            kind="schema_validation",
            artifact_id="schema.lockedspec",
            media_type="application/json",
            produced_by="C1",
        ),
        _make_evidence_artifact(
            chain_repo_root=chain_repo_dir,
            path=command_log_path,
            kind="command_log",
            artifact_id="command.log",
            media_type="application/json",
            produced_by="C1",
        ),
        _make_evidence_artifact(
            chain_repo_root=chain_repo_dir,
            path=chain_repo_dir / rel_policy_inv,
            kind="policy_report",
            artifact_id="policy.invariant_eval",
            media_type="application/json",
            produced_by="C1",
        ),
        _make_evidence_artifact(
            chain_repo_root=chain_repo_dir,
            path=chain_repo_dir / rel_policy_supply,
            kind="policy_report",
            artifact_id="policy.supplychain",
            media_type="application/json",
            produced_by="C1",
        ),
        _make_evidence_artifact(
            chain_repo_root=chain_repo_dir,
            path=chain_repo_dir / rel_policy_adv,
            kind="policy_report",
            artifact_id="policy.adversarial_scan",
            media_type="application/json",
            produced_by="C1",
        ),
        _make_evidence_artifact(
            chain_repo_root=chain_repo_dir,
            path=diff_path,
            kind="diff",
            artifact_id="changes.diff",
            media_type="text/x-diff",
            produced_by="C1",
        ),
    ]

    if tier_id == "tier-1":
        artifacts.append(
            _make_evidence_artifact(
                chain_repo_root=chain_repo_dir,
                path=test_report_path,
                kind="test_report",
                artifact_id="tests.report",
                media_type="application/json",
                produced_by="C1",
            )
        )
        artifacts.append(
            _make_evidence_artifact(
                chain_repo_root=chain_repo_dir,
                path=env_att_path,
                kind="env_attestation",
                artifact_id="env.attestation",
                media_type="application/json",
                produced_by="C1",
            )
        )
    artifacts.sort(key=lambda a: (a.get("kind", ""), a.get("id", ""), a.get("storage_ref", "")))

    evidence_input = {
        "schema_version": "1.0.0",
        "run_id": run_key,
        "artifacts": artifacts,
        "commands_executed": commands_executed,
        "envelope_attestation": envelope_attestation,
    }
    evidence_schema = protocol.read_json("schemas/EvidenceManifest.schema.json")
    if not isinstance(evidence_schema, dict):
        raise ValueError("EvidenceManifest schema must be a JSON object")
    em_errors = validate_schema(
        evidence_input,
        evidence_schema,
        root_schema=evidence_schema,
        path="EvidenceManifest",
    )
    if em_errors:
        first = em_errors[0]
        raise ValueError(f"initial EvidenceManifest invalid at {first.path}: {first.message}")
    _write_json(chain_repo_dir / rel_evidence_input, evidence_input)

    _run_module_expect_rc(
        "chain.gate_q_verify",
        [
            "--repo",
            str(chain_repo_dir),
            "--intent-spec",
            "IntentSpec.core.md",
            "--locked-spec",
            rel_locked,
            "--evidence-manifest",
            rel_evidence_input,
            "--out",
            rel_gate_q,
        ],
    )

    _run_module_expect_rc(
        "chain.gate_r_verify",
        [
            "--repo",
            str(chain_repo_dir),
            "--locked-spec",
            rel_locked,
            "--gate-q-verdict",
            rel_gate_q,
            "--evidence-manifest",
            rel_evidence_input,
            "--r-snapshot-manifest-out",
            rel_r_snapshot,
            "--gate-verdict-out",
            rel_gate_r,
            "--out",
            rel_verify_report,
            "--evaluated-revision",
            repo_head_sha,
        ],
    )

    profile = "public"
    pub_intent = locked_spec.get("publication_intent")
    if isinstance(pub_intent, dict):
        prof = pub_intent.get("profile")
        if isinstance(prof, str) and prof in ("public", "internal"):
            profile = prof

    _run_module_expect_rc(
        "chain.compiler_c3_docs",
        [
            "--repo",
            str(chain_repo_dir),
            "--locked-spec",
            rel_locked,
            "--gate-q-verdict",
            rel_gate_q,
            "--gate-r-verdict",
            rel_gate_r,
            "--r-snapshot-manifest",
            rel_r_snapshot,
            "--out-final-manifest",
            rel_evidence_final,
            "--out-log",
            "docs/docs_compilation_log.json",
            "--out-docs",
            rel_docs,
            "--out-bundle-dir",
            rel_bundle,
            "--out-bundle-root-sha",
            rel_bundle_root_sha,
            "--profile",
            profile,
            "--prompt-block-hashes",
            rel_prompt_hashes,
        ],
    )

    _run_module_expect_rc(
        "chain.seal_bundle",
        [
            "--repo",
            str(chain_repo_dir),
            "--locked-spec",
            rel_locked,
            "--gate-q-verdict",
            rel_gate_q,
            "--gate-r-verdict",
            rel_gate_r,
            "--evidence-manifest",
            rel_evidence_final,
            "--final-commit-sha",
            repo_head_sha,
            "--sealed-at",
            FIXED_SEALED_AT,
            "--signer",
            FIXED_SIGNER,
            "--out",
            rel_seal,
        ],
    )

    _run_module_expect_rc(
        "chain.gate_s_verify",
        [
            "--repo",
            str(chain_repo_dir),
            "--locked-spec",
            rel_locked,
            "--seal-manifest",
            rel_seal,
            "--evidence-manifest",
            rel_evidence_final,
            "--out",
            rel_gate_s,
        ],
    )

    for src_rel, dst_rel in (
        (rel_gate_q, f"{CHAIN_OUT_DIRNAME}/GateVerdict_Q.json"),
        (rel_gate_r, f"{CHAIN_OUT_DIRNAME}/GateVerdict_R.json"),
        (rel_gate_s, f"{CHAIN_OUT_DIRNAME}/GateVerdict_S.json"),
    ):
        src = chain_repo_dir / src_rel
        dst = chain_repo_dir / dst_rel
        if not src.exists() or src.is_symlink() or not src.is_file():
            raise ValueError(f"missing GateVerdict output for bundle check alias: {src}")
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(src.read_bytes())

    chain_paths = _collect_chain_artifact_paths(chain_repo_root=chain_repo_dir, chain_out_dir=chain_out_dir)
    return RunOrchestrationResult(
        chain_repo_dir=chain_repo_dir,
        chain_out_dir=chain_out_dir,
        rel_evidence_final=rel_evidence_final,
        rel_seal=rel_seal,
        rel_gate_s=rel_gate_s,
        chain_paths=chain_paths,
    )
